### ISSUE TITLE
CloudShell error when websocket closes

### ISSUE THREAD

**Issue by bsaby** [Azure/vscode-azureterraform#144]
1. Websocket closed
![image](https://user-images.githubusercontent.com/22470312/37390162-f144878a-27a1-11e8-8db3-b74c27c5fe27.png)

2. run a terraform command
Flash error message quickly and close the Cloudshell, then show the error: terminal process teminated with exit code:1
![image](https://user-images.githubusercontent.com/22470312/37390064-95ccae96-27a1-11e8-8fea-e9556db7d324.png)
![image](https://user-images.githubusercontent.com/22470312/37390068-97e15362-27a1-11e8-97fd-a7a573d4586f.png)

3. run a terraform command again
Occasionally error
![image](https://user-images.githubusercontent.com/22470312/37390080-a9ff23d0-27a1-11e8-831e-e01e3f39501e.png)

**Comment by jdneo** [comment]
Fixed in #146
