### ISSUE TITLE
0.1.1 ENDGAME

### ISSUE THREAD

**Issue by jdneo** [Azure/vscode-azureterraform#158]
## Build
- [ ] Double check the readme
  - [x] @metacpp 
  - [ ] @jeffreyCline 
  - [ ] @achandmsft 
- [x] Update Changelog @jdneo
- [x] Update version @jdneo

## Test
- [x] Regression test @bsaby 

## Release
- [x] Release to market place @jdneo
- [x] Add tag @jdneo
- [x] Edit github release page @jdneo

**Comment by bsaby** [comment]
# Regression test
1. Open regression bug: #160 
2. Test result: 

Test case | Windows | Mac
-- | -- | --
Basic | Pass | Pass
Basic   Command: Init-local | Pass | Pass
Basic   Command: Validate-local | Pass | Pass
Basic   Command: Plan-local | Pass | Pass
Basic   Command: Apply-local | Pass | Pass
Basic   Command: Refresh-local | Pass | Pass
Basic   Command: Destroy-local | Pass | Pass
Basic   Command: Init-cloud shell | Pass | Pass
Basic   Command: Validate-cloud shell | Pass | Pass
Basic   Command: Plan-cloud shell | Pass | Pass
Basic   Command: Apply-cloud shell | Pass | Pass
Basic   Command: Refresh-cloud shell | Pass | Pass
Basic   Command: Destroy-cloud shell | Pass | Pass
Visualize-local | Pass | Pass
Visualize   - cloud shell | Pass | Pass
Push -   local | Pass | Pass
Push -   cloud shell | Pass | Pass

**Comment by metacpp** [comment]
@jdneo README LGTM.
