### ISSUE TITLE
Cloudshell status is wrong after first login

### ISSUE THREAD

**Issue by bsaby** [Azure/vscode-azureterraform#160]
1. Make sure the Azure Account extension has been signed out
2. Select a command: terraform azure -init
3. Click "OK"  to open Cloudshell
4. Click "sign in" to  sign in first

Result: Cloudshell won't be opened after the first login

-------------------------
### Update
Cloud Shell can be opened, but will get an error: `Entry not found in token cache`.

**Comment by jdneo** [comment]
tracking: https://github.com/Microsoft/vscode-azure-account/issues/45

**Comment by jdneo** [comment]
Fixed in: https://github.com/Microsoft/vscode-azure-account/commit/5703e1fbf174a2df094c0f9a8bf684bb07d35876

waiting for release.

**Comment by njuCZ** [comment]
It seems this problem has been fixed by vscode-azure-account, and I can not reproduce this bug myself
