### ISSUE TITLE
Extensions says Terraform is not installed even though it is

### ISSUE THREAD

**Issue by yooakim** [Azure/vscode-azureterraform#176]
When I start VS Code the Azure Terraform extensions says that Terraform is not in my path. But when I enter `terraform -v` in my Integrated terminal terraform works.

This is what I see when I start VS Code:
![capture](https://user-images.githubusercontent.com/862546/39515948-d26164ac-4dfb-11e8-9039-6368b2cb53e3.PNG)

and as shown here Terraform works fine in my Integrated terminal:
![capture-1](https://user-images.githubusercontent.com/862546/39515964-e09b830e-4dfb-11e8-9aba-a0927af3b475.PNG)

I am working on `Windows 10 Version 1803 (OS Build 17134.1)` my VS Code have the following versions:

Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

/Joakim

**Comment by beoSheep** [comment]
I cannot find a solution on Fedora Linux. I have everything in PATH, but VSCODE doesn't see my PATH and this extension doesn't work, no autocomplete, no lint. Any suggestions?

**Comment by yooakim** [comment]
@jdneo sorry this is taking such time, apologise for my late reply. :-) (I've been away over the summer.)

I do have `terraform.exe` in my path, but it is not the default path used by the installation. I've put my terraform.exe in `C:\Users\yooak\OneDrive\Util\terraform.exe` which is available in the path.

**Comment by RadoslavCap** [comment]
> I cannot find a solution on Fedora Linux. I have everything in PATH, but VSCODE doesn't see my PATH and this extension doesn't work, no autocomplete, no lint. Any suggestions?
> 
> EDIT: There is no issue with this extension. Fedora 28 Software Center isn't capable of installing VSCODE as it should. dnf way solved the issue.

The same situation on Fedora 28 with VS Code installed from Flatpak. Application doesn't see binary file copied into /usr/local/bin.

Installation from this guide: https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions works well.

**Comment by njuCZ** [comment]
I can not reproduce this bug locally. If this bug occurs again, I will reopen this issue

**Comment by Frodox** [comment]
How to point vscode for non-standard location? I have something like `/home/user/.bin` in my `$PATH` , but vscode doesn't see it (coz it is in .bashrc )
