### ISSUE TITLE
extension should not prompt on startup

### ISSUE THREAD

**Issue by chrisdias** [Azure/vscode-azureterraform#179]
The terraform extension prompts on startup of vs code if it can't find terraform on the path.  

![image](https://user-images.githubusercontent.com/1487073/41130976-066caf2a-6a6e-11e8-872a-298ab3e8f6db.png)

i think this is generally poor behavior for an extension to prompt on startup every time.  worse though, i've included this extension in the [Azure Extension Pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-azureextensionpack).  Users get a bunch of extensions, and initially they may not need them all.  So having this one prompt on every start becomes especially bad.

At a minimum be a button that says "don't show again".

**Comment by heldersepu** [comment]
I do get this same error and the solution of  "don't show again" is not enough, when this happens the formatting does not work anymore.
For the record I do have terraform on my PATH
