### ISSUE TITLE
Cannot upload files from VSCode to Cloud Shell

### ISSUE THREAD

**Issue by christianreddington** [Azure/vscode-azureterraform#180]
Hi,

I have been trying to use the extension to help me in my Terraform development, however I am unable to push files to Cloud Drive and run them from clouddrive.

I get the following output inside of VSCode:

Attempting to upload files to CloudShell...
Cloudshell terminal opened.
Uploading file c:\Users\<USER>\Documents\<PROJECT>\templates\deploy.tf to cloud shell
Uploading file c:\Users\<USER>\Documents\<PROJECT>\templates\variables.tf to cloud shell

I have looked through the repository, and it appears as though this should be working based on the above output. However, as you'll notice - my clouddrive is empty.

<USER>@Azure:~/clouddrive$ ls -la
total 0
drwxrwxrwx 2 root root 0 May  8 12:58 .cloudconsole
drwxrwxrwx 2 root root 0 May  8 13:09 .pscloudshell

Any thoughts on whether I am doing something wrong here, or how I can debug, or help give any further input to investigate is appreciated.

Thanks!

**Comment by christianreddington** [comment]
I have been looking into the Developer Tools option inside VS Code, and it looks like the below is outputted:

[Extension Host] Error creating FileShare: <Name of file share>

StorageError: Forbidden

However, I have uploaded files to the same File Share using storage explorer (using the same account that is logged into VSCode), so can't seem to identify the issue.

**Comment by JunyiYi** [comment]
Hi @christianreddington , thanks for reporting this issue. This error occurs because you don't have the permission to create a fileshare in the subscription. Could you please check which subscription are you using by typing `az account show`, and confirm whether you have the permission or not?
