### ISSUE TITLE
Won't authenticate using service principal

### ISSUE THREAD

**Issue by scarolan** [Azure/vscode-azureterraform#181]
Steps to reproduce:

1. Install vscode-azureterraform extension
2. Configure service principal settings as environment variables
3. Configure service principal settings again in the settings:

```
    "terminal.integrated.env.windows": {
        "ARM_CLIENT_ID": "*****************************************",
        "ARM_CLIENT_SECRET": "****************************************",
        "ARM_SUBSCRIPTION_ID": "*****************************************",
        "ARM_TENANT_ID": "****************************************"
    },
```

4.  Run `az login`: 
`az login --service-principal -u %ARM_CLIENT_ID% -p %ARM_CLIENT_SECRET% --tenant %ARM_TENANT_ID%`

5.  Attempt to use extension with ctrl-shift-p and selecting "Terraform Lint".

Fails with popup window that says "Azure Service Principal Not Set"

Expected results:  Commands should work with the service principal

Exactly how or where should I be configuring this?  Setting the correct environment variables in both my Windows settings and VSC settings seems not to work.

**Comment by scarolan** [comment]
I should clarify this a bit.  The command I tried to run was `Azure Terraform: Execute Test`.  `Azure Terraform: Plan` seems to work fine.

**Comment by njuCZ** [comment]
"terminal.integrated.env.windows" only inject the env into vscode integrated shell
maybe you only set the env in current shell but not in global, and this extension only read env from global, so it reports "Azure Service Principal Not Set"

I submit a  PR to add workspace configuration for Service Principal, which can avoid such problems
