### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ToROxI** [Azure/vscode-azureterraform#185]
- Issue Type: `Performance`
- Extension Name: `vscode-azureterraform`
- Extension Version: `0.2.2`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/$HOME/ms-azuretools.vscode-azureterraform-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JunyiYi** [comment]
Close the duplicated issue (#196) .
