### ISSUE TITLE
Extension fails to install in a disconnected environment

### ISSUE THREAD

**Issue by Phydeauxman** [Azure/vscode-azureterraform#186]
Attempting to install on a machine that has no Internet connectivity. Extension fails to install throwing error that says: `unable to verify the first certificate`. Version is 0.2.2

**Comment by JunyiYi** [comment]
Hi @Phydeauxman , thanks for reporting the issue. If the error happened during the installation, I believe [VSCode repository](https://github.com/microsoft/vscode/issues) would be a better place to create the issue, because we do not control any installation process as an extension.
