### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fourpastmidnight** [Azure/vscode-azureterraform#188]
[ms-azuretools.vscode-azureterraform-unresponsive.cpuprofile.txt](https://github.com/Azure/vscode-azureterraform/files/2870507/ms-azuretools.vscode-azureterraform-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-azureterraform`
- Extension Version: `0.2.2`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.32.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\cshea\ms-azuretools.vscode-azureterraform-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JunyiYi** [comment]
Close the duplicated issue (#196) .
