### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ELEscarmiente** [Azure/vscode-azureterraform#192]
- Issue Type: `Performance`
- Extension Name: `vscode-azureterraform`
- Extension Version: `0.2.2`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\thomas.berger\ms-azuretools.vscode-azureterraform-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JunyiYi** [comment]
Close the duplicated issue (#196) .
