### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rpus** [Azure/vscode-azureterraform#193]
- Issue Type: `Performance`
- Extension Name: `vscode-azureterraform`
- Extension Version: `0.2.2`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/khalidkhan/ms-azuretools.vscode-azureterraform-unresponsive.cpuprofile.txt`
[ms-azuretools.vscode-azureterraform-unresponsive.cpuprofile.txt](https://github.com/Azure/vscode-azureterraform/files/2958485/ms-azuretools.vscode-azureterraform-unresponsive.cpuprofile.txt)
 :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JunyiYi** [comment]
Close the duplicated issue (#196) .
