### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by davemasino** [Azure/vscode-azureterraform#195]
- Issue Type: `Performance`
- Extension Name: `vscode-azureterraform`
- Extension Version: `0.2.3`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/davem/ms-azuretools.vscode-azureterraform-unresponsive.cpuprofile.txt

`
Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by davemasino** [comment]
[ms-azuretools.vscode-azureterraform-unresponsive.cpuprofile.txt](https://github.com/Azure/vscode-azureterraform/files/3133876/ms-azuretools.vscode-azureterraform-unresponsive.cpuprofile.txt)

**Comment by JunyiYi** [comment]
Close the duplicated issue (#196) .
