### ISSUE TITLE
Deletes are not synchronized

### ISSUE THREAD

**Issue by jnevins-gcm** [Azure/vscode-azureterraform#203]
Deletes of local files don't seem to synchronize to cloud shell storage, even after running Azure Terraform Push. Is this a known bug?

**Comment by jnevins-gcm** [comment]
Anyone maintain this package?

**Comment by JunyiYi** [comment]
Thanks @jnevins-gcm for reporting the issue. @mybayern1974 will be taking care of this repo in the future.
