### ISSUE TITLE
Extension breaks VSCode Remote-SSH functionality

### ISSUE THREAD

**Issue by bkonicek-cs** [Azure/vscode-azureterraform#212]
See https://github.com/microsoft/vscode-remote-release/issues/1689

I found that when I have this extension installed, and have a workspace open that includes Terraform files the Remote-SSH extension stops working.  If I uninstall this extension or remove the folder containing Terraform files from the workspace the Remote-SSH extension starts working again.

VSCode version: 1.40.2
Windows 10 1803
Azure Terraform Extension: 0.3.0 and previous

**Comment by njuCZ** [comment]
the root reason is caused by a dependency. I have upgraded the library,  and test successfully at my local. Thanks for reporting this issue!
