### ISSUE TITLE
This extension breaks functionality for Bicep VSCode extension

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/vscode-azureterraform#222]
See https://github.com/Azure/bicep/issues/626 - the root cause was found to be that the vscode-azureterraform extension was installed. To reproduce, install [vscode-azureterraform](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azureterraform) and [vscode-bicep](https://github.com/Azure/bicep/releases/latest), and try to open a file with a `.bicep` extension.

Is there anything you can think of that could be causing this? This feels similar to https://github.com/Azure/vscode-azureterraform/issues/212.

**Comment by njuCZ** [comment]
the root reason is caused by a dependency. I have upgraded the library,  and test successfully at my local. Thanks for reporting this issue!
