### ISSUE TITLE
Cloud Shell gets stuck

### ISSUE THREAD

**Issue by metacpp** [Azure/vscode-azureterraform#77]
Project: https://github.com/Azure/terraform-azurerm-network

1. Open the Command Palette.
2. Select 'Terraform Azure: execute test', then 'e2e - no ssh' or 'e2e -with ssh'
3. Follow the popup prompt bar on the top to start the Cloud Shell session and choose login.
4. When asking to open page and use given code to authenticate, just click "open".
5. After redirected to login page for code, close the page without typing any code.
6. Repeat 1-4.

You will see below connection info without any progress for quite a long time:
![vscode](https://user-images.githubusercontent.com/1684739/35584698-a3dffb3c-05aa-11e8-8df8-a730e01c4bef.PNG)

Then it will ask for login again, after you follow up all the steps to authenticate the vscode, nothing happen from the debug console, unless you rerun the step 2 in the above.

Expectation: fail as fast as possible and show correct login cloud shell session after retry.

**Comment by jdneo** [comment]
If we close the page without typing any code, the azure account extension will keep waiting for the response from the Server. Thus we cannot get the token and the Cloud Shell cannot be provisioned.

This is an issue that we cannot handle and I'm moving it to the backlog for now.

**Comment by jdneo** [comment]
Fixed with: https://github.com/Microsoft/vscode-azure-account/commit/6b11143fdc8061b36bed6ca3f349f66581c01b68

Waiting for release.

**Comment by jdneo** [comment]
Fixed.
